In [1]:
import torch
import torch.nn.functional as F
import torch.optim as optim

In [2]:
h=torch.tensor([1,0,0,0],dtype=torch.float32)
e=torch.tensor([0,1,0,0],dtype=torch.float32)
l=torch.tensor([1,0,1,0],dtype=torch.float32)
o=torch.tensor([0,0,0,1],dtype=torch.float32)

In [3]:
inputs=[h,e,l,l]
inputs

[tensor([1., 0., 0., 0.]),
 tensor([0., 1., 0., 0.]),
 tensor([1., 0., 1., 0.]),
 tensor([1., 0., 1., 0.])]

In [4]:
Wxh = torch.tensor([0.5,-0.3,0.8,-0.2],requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)
Whh = torch.tensor(0.4,requires_grad=True)
Why = torch.tensor([0.6,-0.3,0.2,0.8], requires_grad=True)

In [5]:
optimizer = optim.SGD([Wxh,b,Whh,Why],lr=0.1)

In [6]:
target = torch.tensor([3])
target

tensor([3])

In [7]:
for epoch in range(100):
    print("="*100)
    h_t= torch.tensor(0.0, dtype=torch.float32)
    for step,x in enumerate(inputs):
        print("="*100)
        print(f"단계 {step+1}")
        print(f"입력 x= {x. numpy()}")
        
        Wxh_x = torch.dot(x,Wxh)+b
        
        print(f"입력 x*Wxh + b={Wxh_x:.4f}")
    
        h_prev=h_t*Whh
        print(f"이전 은닉값 h_t * Whh={h_prev:.4f}")
    
        h_t=torch.tanh(Wxh_x+h_prev)
        print(f"현재 은닉값(h_t):{h_t:.4f}\n")
    
    print("="*100)
    print(f"최종값 계산 과정")
    
    y_raw= Why*h_t
    print(f"회귀 출력(y_raw):{y_raw}")
    y_raw = y_raw.view(1,-1)
    print(f"회귀 출력(y_raw):{y_raw}")
    loss = F.cross_entropy(y_raw, target)
    optimizer.zero_grad()

    loss.backward()
    print(f"loss:{loss.item():.4f}")

    optimizer.step()
    print("업데이트된 가중치")
    print(f"Wxh={Wxh}")
    print(f"b={b}")
    print(f"Whh={Whh}")
    print(f"Why={Why}")

    if(epoch+1)%10==0:
        print("="*100)
        print(f"에폭:{epoch+1}")
        pred_prob = F.softmax(y_raw,dim=1)
        print(f"예측확률:{pred_prob.detach().numpy()}")
        pred_char = torch.argmax(pred_prob).item()
        print(f"예측 인덱스:{pred_char}")
        print(f"예측글자:{['h','e','l','o'][pred_char]}")
    
     

단계 1
입력 x= [1. 0. 0. 0.]
입력 x*Wxh + b=0.5000
이전 은닉값 h_t * Whh=0.0000
현재 은닉값(h_t):0.4621

단계 2
입력 x= [0. 1. 0. 0.]
입력 x*Wxh + b=-0.3000
이전 은닉값 h_t * Whh=0.1848
현재 은닉값(h_t):-0.1146

단계 3
입력 x= [1. 0. 1. 0.]
입력 x*Wxh + b=1.3000
이전 은닉값 h_t * Whh=-0.0459
현재 은닉값(h_t):0.8494

단계 4
입력 x= [1. 0. 1. 0.]
입력 x*Wxh + b=1.3000
이전 은닉값 h_t * Whh=0.3398
현재 은닉값(h_t):0.9274

최종값 계산 과정
회귀 출력(y_raw):tensor([ 0.5565, -0.2782,  0.1855,  0.7420], grad_fn=<MulBackward0>)
회귀 출력(y_raw):tensor([[ 0.5565, -0.2782,  0.1855,  0.7420]], grad_fn=<ViewBackward0>)
los:1.0168
업데이트된 가중치
Wxh=tensor([ 0.5052, -0.2998,  0.8051, -0.2000], requires_grad=True)
b=0.005362723954021931
Whh=0.40393081307411194
Why=tensor([ 0.5721, -0.3121,  0.1808,  0.8592], requires_grad=True)
단계 1
입력 x= [1. 0. 0. 0.]
입력 x*Wxh + b=0.5105
이전 은닉값 h_t * Whh=0.0000
현재 은닉값(h_t):0.4704

단계 2
입력 x= [0. 1. 0. 0.]
입력 x*Wxh + b=-0.2944
이전 은닉값 h_t * Whh=0.1900
현재 은닉값(h_t):-0.1041

단계 3
입력 x= [1. 0. 1. 0.]
입력 x*Wxh + b=1.3156
이전 은닉값 h_t * Whh=-0.0420
현재 은닉값(h